export const appDetails = {
    title: "Chatterbox",
    description: "Generated by create next app",
    whoami: "Lorem ipsum",
    based: "Wroclaw",
}



export type allowedMethods = "PUT" | "POST" | "DELETE" | "GET"

export type Microservice = Record<"auth" | "profile" | "notification" | "chat" | "status", string>;

export const microservices: Microservice = {
    auth: process.env.NEXT_PUBLIC_AUTH_SERVICE_HOST!,
    profile: process.env.NEXT_PUBLIC_PROFILE_SERVICE_HOST!,
    notification: process.env.NEXT_PUBLIC_NOTIFICATION_SERVICE_HOST!,
    chat: process.env.NEXT_PUBLIC_CHAT_SERVICE_HOST!,
    status: process.env.NEXT_PUBLIC_STATUS_SERVICE_HOST!,
};
