services:
  mongo:
    image: mongo:latest
    container_name: notifications_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27018:${MONGO_PORT}"
    networks:
      - notifications_net

networks:
  notifications_net:
    driver: bridge
