basePath: /api/v1
definitions:
  models.Notification:
    properties:
      id:
        description: Unique identifier for the notification
        type: string
      info:
        description: Information/content of the notification
        type: string
      isDelivered:
        description: Flag indicating whether the notification has been delivered
        type: boolean
      sentAt:
        description: Timestamp when the notification was sent
        type: string
      sub:
        description: Subject of the notification
        type: string
      userID:
        description: The ID of the user receiving the notification
        type: string
    type: object
host: localhost:8003
info:
  contact: {}
  description: Notification delivery service
  title: Notification Service API
  version: "1.0"
paths:
  /notifications:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of notifications for a given user ID
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of notifications per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of notifications
          schema:
            items:
              $ref: '#/definitions/models.Notification'
            type: array
        "400":
          description: Invalid request
      summary: Get user notifications with pagination
      tags:
      - notifications
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
